# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = ["btrfs"];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1a93a7ed-15be-4d7a-a1c2-098123eef27c";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."enc".device = "/dev/disk/by-uuid/de9f9ea5-c3c7-472c-9cf8-f6270cfe8f34";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/c5f8bccc-8909-4c8c-b794-d93d80444eeb";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" "noatime" ];
    };

  boot.initrd.luks.devices."data".device = "/dev/disk/by-uuid/c94209ae-8acd-4a8f-b12e-eb5c0a4c1cd4";

  fileSystems."/mnt/games" =
    { device = "/dev/disk/by-uuid/c5f8bccc-8909-4c8c-b794-d93d80444eeb";
      fsType = "btrfs";
      options = [ "subvol=@games" "compress=zstd" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B5E5-CC61";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ 
    { 
      device = "/dev/disk/by-partuuid/3dc19267-1965-4970-ae4b-020c3a2ce834";
      randomEncryption.enable = true;
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
