# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/dce9c459-4e18-4454-acd3-8441a6f02fb0";
      fsType = "xfs";
    };

  boot.initrd.luks.devices."enc".device = "/dev/disk/by-uuid/0a455100-9758-4379-b420-219f83906501";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7A7E-C0E4";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/mnt/games" =
    { device = "/dev/disk/by-uuid/166ebfa1-0f29-464c-8318-987401a22087";
      fsType = "xfs";
    };

  boot.initrd.luks.devices."games".device = "/dev/disk/by-uuid/f5f9a285-e078-4a50-8335-48645c35ec80";

  swapDevices =
    [ { device = "/dev/disk/by-partuuid/cfeb80ca-a404-47d1-bb33-f074f90d0869"; randomEncryption.enable = true; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
