# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = ["btrfs" "zfs" "xfs"];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/52985543-f7b9-4222-b577-a0e5c73af9ec";
      fsType = "xfs";
    };

    boot.initrd.luks.devices."enc".device = "/dev/disk/by-uuid/89918b3c-b6a5-4069-8f3e-f38d9e10c141";
  boot.initrd.luks.devices."games".device = "/dev/disk/by-uuid/ffc87718-85c1-4780-9209-f7b17828ba7";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/8dfeec9e-87b3-426f-a2ae-7231b001d9a6";
      fsType = "btrfs";
      options = [ "subvol=@home"  "compress=zstd" "noatime" "discard=async" "ssd" "space_cache=v2" ];
    };

  boot.initrd.luks.devices."home".device = "/dev/disk/by-uuid/6b9e149b-c7e3-4a76-ae2c-8ab127ab619e";

  fileSystems."/mnt/games" =
    { device = "/dev/disk/by-uuid/bad99577-2f00-4040-a6c6-167c072aa801";
      fsType = "btrfs";
      options = [ "subvol=@games"  "compress=zstd" "noatime" "discard=async" "ssd" "space_cache=v2" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B2B4-D07E";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/export/media" = {
    device = "/mnt/media";
    options = [ "bind" ];
  };

  fileSystems."/export/documents" = {
    device = "/mnt/documents";
    options = [ "bind" ];
  };

  fileSystems."/export/projects" = {
    device = "/mnt/projects";
    options = [ "bind" ];
  };

  swapDevices =
    [ { device = "/dev/disk/by-partuuid/b193effd-c695-4c73-9358-b1f517bcea39";
        randomEncryption.enable = true;}
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
