# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "xfs" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/233003a6-a049-4262-86d5-5c07e895a787";
      fsType = "xfs";
    };

  boot.initrd.luks.devices."enc".device = "/dev/disk/by-uuid/6f122743-24ad-4fff-867c-27237c0505a0";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2196-66C3";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/mnt/games" =
    { device = "/dev/disk/by-uuid/31ac0cc5-e7eb-419f-ae2c-f209d364af32";
      fsType = "xfs";
    };

  boot.initrd.luks.devices."games".device = "/dev/disk/by-uuid/3eb02ae3-d346-49ba-bdd8-b0aeaff1db45";

  swapDevices =
    [ { device = "/dev/disk/by-partuuid/ddd76945-40da-47bb-8e64-eb1e66649b00"; 
        randomEncryption.enable = true;
	}
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
