name: Build pkgs

on:
  workflow_call:
    secrets:
      CACHIX_AUTH_TOKEN:
        required: false

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        package:
          - mactahoe-theme

    with:
      command: nix build -L .#${{ matrix.package }}
    secrets: inherit
