name: Build pkgs

on:
  workflow_call:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - mactahoe-theme

    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - name: Build package
        run: nix build -L .#${{ matrix.package }}

    secrets: inherit

