name: Nix

on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string


jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main

      - run: ${{ inputs.command }}
